extends: default

ignore: |
  chart/templates/**

rules:
  document-start: disable
  truthy: disable
  line-length:
    max: 120
    level: warning
  trailing-spaces: enable
  new-line-at-end-of-file: enable
  empty-lines:
    max: 1
    max-start: 0
    max-end: 0